### ISSUE TITLE
gdaxConsole error: 'price' does not exist in type 'StopOrder'

### ISSUE THREAD

**Issue by markshust** [coinbase/coinbase-pro-trading-toolkit#107]
getting the following error when running `ts-node src/consoles/gdaxConsole.ts --product BTC-USD -t`

```
/usr/local/n/lib/node_modules/ts-node/src/index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
src/exchanges/gdax/GDAXExchangeAPI.ts (219,21): Type '{ type: "stop"; product_id: string; side: "buy" | "sell"; size: string; price: string; funds: str...' is not assignable to type 'OrderParams'.
  Object literal may only specify known properties, and 'price' does not exist in type 'StopOrder'. (2322)
    at getOutput (/usr/local/n/lib/node_modules/ts-node/src/index.ts:307:15)
    at /usr/local/n/lib/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/usr/local/n/lib/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/usr/local/n/lib/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (module.js:623:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/local/n/lib/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
```

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
