### ISSUE TITLE
Trader placeOrder catch err.asMessage UnhandledRejection

### ISSUE THREAD

**Issue by userings** [coinbase/coinbase-pro-trading-toolkit#255]
I got the following unhandled promise rejecting warning when placing an order using trader.

```
(node:9396) UnhandledPromiseRejectionWarning: TypeError: err.asMessage is not a function
    at api.placeOrder.then.catch (D:\code-rep\new-arb-bot\node_modules\gdax-trading-toolkit\src\core\Trader.ts:106:68)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:9396) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)ejection id: 26)
```

windows, Node v10, gdax-trading-toolkit v0.3.1.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
